apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: tap-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-express
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/J-kolaric/node-express
